name: Build and Release

on:
  push:
    branches:
      - main
      - beta
    paths-ignore:
      - "**.md"
      - .editorconfig
      - .gitignore
      - LICENSE
  pull_request:
    paths-ignore:
      - "**.md"
      - .editorconfig
      - .gitignore
      - LICENSE

permissions:
  contents: read

jobs:
  build-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install

      - name: Compile the API
        working-directory: ./packages/api
        run: bun run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: api-artifact
          path: packages/api/lib

  build-server:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install

      - name: Compile the Server
        working-directory: ./packages/server
        run: bun run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: server-artifact
          path: packages/server/lib

  release-api:
    runs-on: ubuntu-latest
    needs: 
      - build-api
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Download API Artifact
        uses: actions/download-artifact@v5
        with:
          name: api-artifact

      - name: Install Semantic Release
        run: npm i -g semantic-release semantic-release-monorepo @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github

      - name: Release
        working-directory: ./packages/api
        run: npm run semantic-release -e semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-server:
    runs-on: ubuntu-latest
    needs: 
      - build-server
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Download Server Artifact
        uses: actions/download-artifact@v5
        with:
          name: server-artifact

      - name: Install Semantic Release
        
      - name: Install Semantic Release
        run: npm i -g semantic-release semantic-release-monorepo @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github

      - name: Release
        working-directory: ./packages/server
        run: npm run semantic-release -e semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
