name: CI/CD

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint lexicon files
        uses: birbhouse-games/lexicon-tools/lint@v1
        with:
          lexicon-path: ./src
          failure-threshold: error

  # breaking:
  #   name: Check Breaking Changes
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6

  #     - name: Check for breaking changes
  #       uses: birbhouse-games/lexicon-tools/breaking@v1
  #       with:
  #         lexicon-path: ./src

  publish:
    name: Publish Lexicons
    runs-on: ubuntu-latest
    # needs: [lint, breaking]
    needs: [lint]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Publish lexicons
        uses: birbhouse-games/lexicon-tools/publish@v1
        with:
          lexicon-path: ./src
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.APP_PASSWORD }}
          update: "true"
